### ISSUE TITLE
A little problem

### ISSUE THREAD

**Issue by JiahengZeng** [christopher-hsu/scalableMARL#1]
Hello, I'm a graduate student in grade one. I'm very interested in your article and code. I installed the environment according to your instructions and ran your code without adjusting any code content and by default. The following error occurred:

Traceback (most recent call last):
  File "algos/maTT/run_script.py", line 181, in <module>
    results = train(seed, save_dir)
  File "algos/maTT/run_script.py", line 90, in train
    doubleQlearning(
  File "/home/zjh/scalableMARL/algos/maTT/dql.py", line 362, in doubleQlearning
    batch = replay_buffer.sample_batch(batch_size)#, env.num_targets)
  File "/home/zjh/scalableMARL/algos/maTT/replay_buffer.py", line 104, in sample_batch
    return self._encode_sample(batch_size, idxes, nb_targets)
  File "/home/zjh/scalableMARL/algos/maTT/replay_buffer.py", line 64, in _encode_sample
    batch['obs'][i] = obs_t
ValueError: could not broadcast input array from shape (2,6) into shape (2,5)

I will study your code carefully. But since you are more familiar with your code, are there some small problems that you can solve immediately? If it runs successfully, I believe it can better help me understand the code. Thank you

**Comment by christopher-hsu** [comment]
Thank you for the question, it should be fixed now! The issue was in "envs/maTTenv/env/setTracking-v0.py", line 55. The self.limit['state'] had the incorrect number of dimensions and was in fact missing one.
